# Generated by Django 3.1 on 2022-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
